//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDropDownProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UFirstName { get; set; }
        public string ULastName { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> SID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
